/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as Careers1RouteImport } from './routes/careers1'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as ServicesRegulatoryComplianceRouteImport } from './routes/services.regulatory-compliance'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const Careers1Route = Careers1RouteImport.update({
  id: '/careers1',
  path: '/careers1',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRegulatoryComplianceRoute =
  ServicesRegulatoryComplianceRouteImport.update({
    id: '/services/regulatory-compliance',
    path: '/services/regulatory-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/careers1': typeof Careers1Route
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/research': typeof ResearchRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/regulatory-compliance': typeof ServicesRegulatoryComplianceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/careers1': typeof Careers1Route
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/research': typeof ResearchRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/services/regulatory-compliance': typeof ServicesRegulatoryComplianceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/careers1': typeof Careers1Route
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/research': typeof ResearchRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/regulatory-compliance': typeof ServicesRegulatoryComplianceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/careers1'
    | '/case-studies'
    | '/contact'
    | '/education'
    | '/research'
    | '/blogs/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blogs/'
    | '/services/regulatory-compliance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/careers1'
    | '/case-studies'
    | '/contact'
    | '/education'
    | '/research'
    | '/blogs/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blogs'
    | '/services/regulatory-compliance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/careers1'
    | '/case-studies'
    | '/contact'
    | '/education'
    | '/research'
    | '/blogs/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blogs/'
    | '/services/regulatory-compliance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  Careers1Route: typeof Careers1Route
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ResearchRoute: typeof ResearchRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ServicesRegulatoryComplianceRoute: typeof ServicesRegulatoryComplianceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers1': {
      id: '/careers1'
      path: '/careers1'
      fullPath: '/careers1'
      preLoaderRoute: typeof Careers1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
    '/services/regulatory-compliance': {
      id: '/services/regulatory-compliance'
      path: '/services/regulatory-compliance'
      fullPath: '/services/regulatory-compliance'
      preLoaderRoute: typeof ServicesRegulatoryComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  Careers1Route: Careers1Route,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ResearchRoute: ResearchRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ServicesRegulatoryComplianceRoute: ServicesRegulatoryComplianceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
